Last Documents added
Ditmar/plagiarist-g2 pull request #2
Opened 2022-12-13 08:01 UTC by RojoRX

Agregue el componente para mostrar los últimos documentos publicados, no logro encontrar la url de la api que necesito para recibir estos datos, por lo que uso de momento otra api para probar que lo demás funciona correctamente

2022-12-14 03:21 UTC, Ditmar requested changes
Please use useEffect the fetch function should be into the async firectory, use the functions created in https://github.com/Ditmar/plagiarist-g2/blob/master/src/async/api.js to make the request

2022-12-14 03:21 UTC, Ditmar commented on src/components/LastDocsComponent/LastDocs.jsx
> +        fetch('https://fakestoreapi.com/products?limit=5').then(res => res.json()).then(json => {
componentDidMount is using in react with classes, that is, react legacy, in this case, we are using react with a hook if you need to control the fetch you need to put the request, into the useEffect function,

2022-12-14 03:21 UTC, Ditmar commented on src/components/DashboardComponent/Orders.jsx
> +                    this.state.items.map((row) => (
Please try to separate this large conde in small components

2022-12-14 05:33 UTC, RojoRX commented
Good evening Engineer. I corrected the code problems, now using useEffect and making the code shorter with other components

2022-12-14 18:56 UTC, Ditmar requested changes
don't use classes use hooks

2022-12-14 18:56 UTC, Ditmar commented on src/components/DashboardComponent/Orders.jsx
> +    constructor(props) {
We are using react with hooks , no React with classes

2022-12-14 19:26 UTC, RojoRX commented
Good afternoon engineer. Fixed the changes, forgot I was using Orders.jsx as a test at the start. Now all my code is in the LastDocsComponent with the requested changes and I removed my code from Orders.jsx

2022-12-15 01:17 UTC, Ditmar approved these changes
approved

2022-12-15 01:17 UTC, Ditmar commented on src/components/LastDocsComponent/services/call.js
> +    state(await response.json())
nice

2022-12-15 01:17 UTC, merged